name: CI-CD

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test-build-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          pip install -r app/requirements.txt

      - name: Run tests
        run: |
          python -m pytest -q

      - name: Log in to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: |
          IMAGE=ghcr.io/${{ github.repository }}/tp2-flask:$(echo $GITHUB_SHA | head -c7)
          docker build -t $IMAGE .
          docker tag $IMAGE ghcr.io/${{ github.repository }}/tp2-flask:latest

      - name: Push image
        run: |
          docker push ghcr.io/${{ github.repository }}/tp2-flask:latest
          docker push ghcr.io/${{ github.repository }}/tp2-flask:$(echo $GITHUB_SHA | head -c7)